apiVersion: apps/v1
kind: Deployment
metadata:
  name: moodai-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moodai-db
  template:
    metadata:
      labels:
        app: moodai-db
    spec:
      containers:
      - name: postgres
        image: postgres:15
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: moodai-secrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: moodai-secrets
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          value: "moodai_db"
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: moodai-db
spec:
  selector:
    app: moodai-db
  ports:
  - port: 5432
    targetPort: 5432
  type: ClusterIP

